sudo: false
language: node_js
node_js:
  - "node"
before_install:
  - npm install -qg bower gulp-cli
  - npm install -q
  - bower install --force
script:
  - gulp test
group: stable
dist: precise
os: linux