language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - npm install -g gulp-cli
  - npm install phantomjs
  - npm install -g karma
  - bower install
  - gulp default
script: gulp test